Attempt to make bootstrap a complete setup script.
I was able to go from zero-to-hero with this on OSX. I will note I had
all of the dependencies installed already so there might be tweaks
necessary to the list for brew.

Added a script to generate a secret key used by bootstrap when creating
the default database file. Also created a simpler MongoDB start script.
Regardless of the system you are on it will work. It may not be 100%
performant since we're not paying any attention to NUMA, but if you are
just looking to get a system up and running, this will work.

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -4,9 +4,11 @@
 #
 # Usage: script/bootstrap
 # This script is designed to install all of the necessary dependencies for a
-# CRITs install.
+# CRITs install, walk through some basic setup, and help you start a quick
+# instance of CRITs.
 
 
+# Make sure we are working with a 64-bit system.
 ARCH=$(uname -m | sed 's/x86_//;s/i[3-6]86/32/')
 echo "Architecture: $ARCH"
 
@@ -17,6 +19,7 @@ if [ $ARCH -ne '64' ]; then
   exit
 fi
 
+# Determine the OS we are working with.
 # Using lsb-release because os-release not available on Ubuntu 10.04
 if [ -f /etc/lsb-release ]; then
   . /etc/lsb-release
@@ -33,12 +36,14 @@ fi
 OS="$(tr "[:upper:]" "[:lower:]" <<< "$OS")"
 VER="$(tr "[:upper:]" "[:lower:]" <<< "$VER")"
 
+# Ubuntu: Install as many dependencies as we can using apt-get.
 if [ "$OS" == 'ubuntu' ]
 then
   echo "Installing dependencies with apt-get"
   apt-get update
   apt-get install -y --fix-missing apache2 build-essential curl git libapache2-mod-wsgi libevent-dev libz-dev libfuzzy-dev libldap2-dev libpcap-dev libpcre3-dev libsasl2-dev libxml2-dev libxslt1-dev libyaml-dev mongodb numactl p7zip-full python-dev python-pip ssdeep upx zip
 
+# Redhat: Install as many dependencies as we can using yum.
 # TODO: Need to test centos dependencies
 # elif [ "$OS" == 'centos' ] || [ "$OS" == 'redhat' ]
 elif [ "$OS" == 'red hat' ]
@@ -54,6 +59,7 @@ then
   sudo yum install libyaml-0.1.4-1
   sudo yum install upx-3.07-1
 
+# OSX: Install as many dependencies as we can using Homebrew.
 elif [ "$OS" == 'darwin' ]
 then
   command -v brew >/dev/null 2>&1 || {
@@ -67,6 +73,8 @@ else
   exit
 fi
 
+# Determine if MongoDB is already installed.
+# NOTE: This does not do a version check, which we should probably do somehow.
 command -v mongo >/dev/null 2>&1 || {
   echo "Installing MongoDB 2.6.4..."
   curl http://downloads.mongodb.org/linux/mongodb-linux-x86_64-2.6.4.tgz > mongodb-linux-x86_64-2.6.4.tgz
@@ -76,7 +84,60 @@ command -v mongo >/dev/null 2>&1 || {
   rm -r mongodb-linux-x86_64-2.6.4
 }
 
+# Install the rest of our dependencies which are python libraries.
 echo "Installing Python Dependencies"
 sudo pip install -r requirements.txt
 
 echo "Dependency installations complete!"
+
+# Create log file and generate default database configuration.
+echo "Setting up crits.log file"
+touch logs/crits.log
+chmod 664 logs/crits.log
+
+echo "Creating default database configuration file"
+cp crits/config/database_example.py crits/config/database.py
+SC="$(python contrib/gen_secret_key.py)"
+sed -i '' -e "s/.*SECRET_KEY.*/SECRET_KEY = \'"$SC"\'/" crits/config/database.py
+
+# If MongoDB isn't already running, ask to start it.
+# This can fail if MongoDB is running already but on a non-standard port.
+pgrep mongod &> /dev/null
+if [ $? == 1 ]
+then
+  while true; do
+    read -p "Do you want to start 'mongod' now? [yn] " yn
+    case $yn in
+        [Yy]* ) mkdir -p /data/db; mkdir -p /data/logs; sh contrib/mongo/mongod_start.sh; break;;
+        [Nn]* ) break;;
+        * ) echo "Please answer yes or no.";;
+    esac
+  done
+fi
+
+echo "Creating default collections"
+python manage.py create_default_collections
+
+# Setup the first admin user.
+read -p "Username: " USERNAME
+read -p  "First name: " FIRSTNAME
+read -p "Last name: " LASTNAME
+read -p "Email address: " EMAIL
+read -p "Organization name: " ORG
+
+echo "Adding a default admin account"
+python manage.py users -a -A -e "$EMAIL" -f "$FIRSTNAME" -l "$LASTNAME" -o "$ORG" -u "$USERNAME"
+echo "Make note of the above password so you can authenticate!"
+
+# Attempt to start the runserver.
+while true; do
+  read -p "Do you want to start 'runserver' now? [yn] " yn
+  case $yn in
+      [Yy]* ) break;;
+      [Nn]* ) exit;;
+      * ) echo "Please answer yes or no.";;
+  esac
+done
+
+echo "Attempting to start runserver on port 8080"
+python manage.py runserver 0.0.0.0:8080
